services:
  php:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: ci
    volumes:
      - ./app:/app
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: testing
      DB_HOST: mysql
      DB_NAME: app_test
      DB_USER: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_test
    tmpfs:
      - /var/lib/mysql

  redis:
    image: redis:7
